services:
  nginx:
    image: nginx:mainline-alpine
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - api-source:/usr/share/nginx/html/
    depends_on:
      - php
      - node
    container_name: "nginx"

  php:
    build:
      context: './php/'
      args:
        PHP_VERSION: 8.3
    networks:
      - backend
    volumes:
      - api-source:/usr/share/nginx/html/
    container_name: "php"

  node:
    image: node:18
    networks:
      - frontend
    volumes:
      - frontend-source:/usr/src/
    working_dir: /usr/src/app
    command: ["npm", "start"]
    container_name: "node"

  mariadb:
    image: mariadb:latest
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: "db"

volumes:
  api-source:
  frontend-source:
  database:
networks:
  backend:
  frontend:
