version: '3.8'

services:
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - php
      - node
      - mariadb
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - api-source:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: "web"

  php:
    build:
      context: './php/'
      args:
        PHP_VERSION: 8.3
    networks:
      - backend
    volumes:
      - api-source:/usr/share/nginx/html/
    container_name: "php"

  mariadb:
    image: mariadb:latest
    restart: always
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - ./database/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: "db"

  node:
    build:
      context: './node/'
    networks:
      - frontend
    volumes:
      - front-source:/usr/src/app
    ports:
      - "3000:3000"
    container_name: "node"

volumes:
  api-source:
  front-source:
networks:
  backend:
  frontend:
