services:
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - php
      - mariadb
    networks:
      backend:
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: "web"
  php:
    build:
      context: './php/'
      args:
        PHP_VERSION: 8.3
    networks:
      backend:
    volumes:
      - ./htdocs/:/usr/share/nginx/html/
    container_name: "php"
  mariadb:
    build:
      context: './mariadb/'
      args:
        MARIADB_VERSION: "latest"
    restart: always
    networks:
      backend:
    ports:
      - 3306:3306
    volumes:
      - ./database/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: "db"

networks:
  backend: